image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

build_script:
  - ps: sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - ps: sudo chmod +x /usr/local/bin/docker-compose
  - ps: sudo docker-compose up -d
  - sleep 20
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/aqa-shop.jar &
  - sleep 15
  - cd gate-simulator && npm start &
  - sleep 10
  - chmod +x gradlew
  - ./gradlew test --info "-Dselenide.headless=true" # запускаем тесты в headless режиме, флаг --info позволяет выводить больше информации